//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQEntityBaseExample.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RetrieveCustomerDataByID", ReplyAction="http://tempuri.org/IService/RetrieveCustomerDataByIDResponse")]
        LINQEntityBaseExampleData.Customer RetrieveCustomerDataByID(out string DBLog, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateCustomerData", ReplyAction="http://tempuri.org/IService/UpdateCustomerDataResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DBLog")]
        string UpdateCustomerData(LINQEntityBaseExampleData.Customer ModifiedCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductData", ReplyAction="http://tempuri.org/IService/GetProductDataResponse")]
        LINQEntityBaseExampleData.Product[] GetProductData(out string DBLog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServiceChannel : LINQEntityBaseExample.WCFService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<LINQEntityBaseExample.WCFService.IService>, LINQEntityBaseExample.WCFService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LINQEntityBaseExampleData.Customer RetrieveCustomerDataByID(out string DBLog, string CustomerID) {
            return base.Channel.RetrieveCustomerDataByID(out DBLog, CustomerID);
        }
        
        public string UpdateCustomerData(LINQEntityBaseExampleData.Customer ModifiedCustomer) {
            return base.Channel.UpdateCustomerData(ModifiedCustomer);
        }
        
        public LINQEntityBaseExampleData.Product[] GetProductData(out string DBLog) {
            return base.Channel.GetProductData(out DBLog);
        }
    }
}
